### ISSUE TITLE
Not working on sense

### ISSUE THREAD

**Issue by delabusy** [missreya/nyancat-fitbit#1]
Really like this -- can't load on Fitbit Sense though, receiving following: 

`TS5083: Cannot read file '/project/node_modules/@fitbit/sdk/sdk-tsconfig.json'.`
`TS18003: No inputs were found in config file '/project/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.`
`Error: Failed to parse tsconfig`
`Build failed.`

**Comment by missreya** [comment]
Thank you so much for notifying me of this issue with the error! I'll see if I can replicate the issue on my end soon.

**Comment by missreya** [comment]
Happy new year!

It looks like the node modules that are generated through Fitbit's development CLI project creation are not required when running the clock in Fitbit Studio, but they are needed in any other IDE (in this case I am using VS Code). 

I've pushed a new folder called "node_modules" to this build - please download this and see if this fixes it on your end as well. Thanks!
